language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js: 
  - '12'

git:
  depth: 3

script:
  - yarn test

notificacion:
  email:
    recipients:
        - r.livise+travis@hotmail.com
        - r.livise.l+travis@gmail.com
      on_success: always
      on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: f58fac57-6f09-486f-bb42-66efecda5411
  app: platzi-store-backend-1
  on:
    repo: R-Livise/platzi-store-backend
